CREATE TABLE client(
    id_client NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    prénom VARCHAR2(100) NOT NULL,
    nom VARCHAR2(100) NOT NULL,
    date_naissance DATE DEFAULT SYSDATE NOT NULL,
    email VARCHAR2(100)
);
INSERT INTO client (prénom, nom, email) VALUES ('James', 'Bond', 'jbond@gmail.com');
INSERT INTO client (prénom, nom, email) VALUES ('Justin', 'Bieber', 'jbieber@gmail.com');


CREATE TABLE avion (
    "ID_AVION" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 NOT NULL, 
    "COULEUR" VARCHAR2(100 BYTE) DEFAULT 'Blanc', 
    "MODÈLE" VARCHAR2(100 BYTE) NOT NULL, 
    "COMPAGNIE" VARCHAR2(100 BYTE) NOT NULL, 
    PRIMARY KEY ("ID_AVION")
);


INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (41, 'Bleu', 'Embraer 195 E2', 'Porter Airlines');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (42, 'Bleu', 'Embraer 195 E2', 'Air Transat');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (1, 'Bleu', 'Airbus A350-300', 'French BEE');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (2, 'Blanc', 'Boeing 777-200/200ER', 'Air France');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (3, 'Blanc', 'Boeing 789-9 Dreamliner', 'Air New Zaeland');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (4, 'Bleu', 'Airbus A330-300', 'Air Transat');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (5, 'Rouge et Blanc', 'Airbus A220-300', 'Air Canada');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (6, 'Blanc', 'Airbus A321-100/200', 'Air Transat');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (21, 'Blanc', 'Boeing 737 MAX 8', 'Air New Zealand');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (22, 'Bleu', 'Boeing 737 MAX 8', 'Aeromexico');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (23, 'Bleu', 'Boeing 737 MAX 8', 'United Airlines');

INSERT INTO avion("ID_AVION", "COULEUR", "MODÈLE", "COMPAGNIE") 
VALUES (24, 'Blanc', 'Boeing 737 MAX 8', 'Westjet');

COMMIT;



CREATE TABLE départ (
    "CODE_IATA" VARCHAR2(3 BYTE) NOT NULL, 
    "PAYS" VARCHAR2(100 BYTE) NOT NULL, 
    "CAPACITÉ" NUMBER, 
    "VILLE" VARCHAR2(255 BYTE) DEFAULT 'Inconnue' NOT NULL, 
    
    -
    PRIMARY KEY ("CODE_IATA")
);


INSERT INTO départ("CODE_IATA", "PAYS", "CAPACITÉ", "VILLE") 
VALUES ('YUL', 'Canada', 200, 'Montréal');

INSERT INTO départ("CODE_IATA", "PAYS", "CAPACITÉ", "VILLE") 
VALUES ('PNX', 'États-Unis', 250, 'Inconnue');

INSERT INTO départ("CODE_IATA", "PAYS", "CAPACITÉ", "VILLE") 
VALUES ('TYO', 'Japon', 300, 'Inconnue');

INSERT INTO départ("CODE_IATA", "PAYS", "CAPACITÉ", "VILLE") 
VALUES ('ORY', 'France', 200, 'Inconnue');

INSERT INTO départ("CODE_IATA", "PAYS", "CAPACITÉ", "VILLE") 
VALUES ('CBR', 'Australie', 250, 'Inconnue');

INSERT INTO départ("CODE_IATA", "PAYS", "CAPACITÉ", "VILLE") 
VALUES ('TLC', 'Mexique', 300, 'Inconnue');


COMMIT;

CREATE TABLE destination (
    "CODE_IATA"            VARCHAR2(3 BYTE) NOT NULL, 
    "PAYS"                 VARCHAR2(100 BYTE) NOT NULL, 
    "CAPACITÉ"             NUMBER, 
    "IMAGE_DE_DESTINATION" VARCHAR2(100 BYTE) NOT NULL, 
    "EN_FEU"               BOOLEAN NOT NULL, 
    "VILLE"                VARCHAR2(255 BYTE) DEFAULT 'Inconnue' NOT NULL, 
    
    
    PRIMARY KEY ("CODE_IATA")
);


INSERT INTO destination("CODE_IATA", "PAYS", "CAPACITÉ", "IMAGE_DE_DESTINATION", "EN_FEU", "VILLE") 
VALUES ('YVR', 'Canada', NULL, 'vancouver.jpg', false, 'Vancouver');

INSERT INTO destination("CODE_IATA", "PAYS", "CAPACITÉ", "IMAGE_DE_DESTINATION", "EN_FEU", "VILLE") 
VALUES ('PNX', 'États-Unis', 250, 'texas.jpg', false, 'Texas');

INSERT INTO destination("CODE_IATA", "PAYS", "CAPACITÉ", "IMAGE_DE_DESTINATION", "EN_FEU", "VILLE") 
VALUES ('TYO', 'Japon', 300, 'tokyo.jpg', false, 'Tokyo');

INSERT INTO destination("CODE_IATA", "PAYS", "CAPACITÉ", "IMAGE_DE_DESTINATION", "EN_FEU", "VILLE") 
VALUES ('ORY', 'France', 200, 'france.jpg', true, 'Paris');

INSERT INTO destination("CODE_IATA", "PAYS", "CAPACITÉ", "IMAGE_DE_DESTINATION", "EN_FEU", "VILLE") 
VALUES ('CDG', 'France', 1500, 'france.jpg', false, 'Paris');

INSERT INTO destination("CODE_IATA", "PAYS", "CAPACITÉ", "IMAGE_DE_DESTINATION", "EN_FEU", "VILLE") 
VALUES ('SYD', 'Australie', 1500, 'australie.jpg', false, 'Sydney');

INSERT INTO destination("CODE_IATA", "PAYS", "CAPACITÉ", "IMAGE_DE_DESTINATION", "EN_FEU", "VILLE") 
VALUES ('LAX', 'États-Unis', 5000, 'LosAngeles.jpg', true, 'Los-Angeles');

INSERT INTO destination("CODE_IATA", "PAYS", "CAPACITÉ", "IMAGE_DE_DESTINATION", "EN_FEU", "VILLE") 
VALUES ('CUN', 'Mexique', 5000, 'mexique.jpg', true, 'Cancun');

INSERT INTO destination("CODE_IATA", "PAYS", "CAPACITÉ", "IMAGE_DE_DESTINATION", "EN_FEU", "VILLE") 
VALUES ('SEA', 'États-Unis', 5000, 'seattle.jpg', false, 'Seatle');


COMMIT;

CREATE TABLE billet (
    "ID_BILLET" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 NOT NULL, 
    "ID_CLIENT" NUMBER NOT NULL, 
    "ID_VOL" NUMBER NOT NULL, 
    "CLASSE" VARCHAR2(100 BYTE) NOT NULL, 
    "PRIX" NUMBER(10,2) NOT NULL, 
    "DATE_CRÉÉ" DATE DEFAULT SYSDATE NOT NULL, 
    "DATE_DÉPART" DATE NOT NULL, 
    "DATE_ARRIVÉ" DATE NOT NULL, 
    "HEURE_DÉPART" VARCHAR2(100 BYTE), 
    "HEURE_ARRIVÉE" VARCHAR2(100 BYTE), 
    
    
    PRIMARY KEY ("ID_BILLET"),
    
    
    CONSTRAINT "FK_CLIENT" FOREIGN KEY ("ID_CLIENT") REFERENCES client("ID_CLIENT"), 
    CONSTRAINT "FK_VOL" FOREIGN KEY ("ID_VOL") REFERENCES vol("ID_VOL")
);



CREATE TABLE vol (
    "ID_VOL"                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 NOT NULL, 
    "ID_AVION"              NUMBER NOT NULL, 
    "CODE_IATA_DÉPART"      VARCHAR2(3 BYTE) NOT NULL, 
    "CODE_IATA_DESTINATION" VARCHAR2(3 BYTE) NOT NULL, 
    "DURÉE_DE_VOL"          INTERVAL DAY (2) TO SECOND (6), 
    "CARBURANT_CONSOMMER"   NUMBER(10,2), 
    "PRIX"                  NUMBER NOT NULL, 
    "TRANSFER"              NUMBER DEFAULT 0 NOT NULL, 
    
    -- Clé primaire
    PRIMARY KEY ("ID_VOL"),
    
   
    CONSTRAINT "FK_AVION" FOREIGN KEY ("ID_AVION") REFERENCES avion("ID_AVION"), 
    CONSTRAINT "FK_DÉPART" FOREIGN KEY ("CODE_IATA_DÉPART") REFERENCES départ("CODE_IATA"), 
    CONSTRAINT "FK_DESTINATION" FOREIGN KEY ("CODE_IATA_DESTINATION") REFERENCES destination("CODE_IATA")
);


INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (44, 41, 'YUL', 'YVR', TO_DSINTERVAL('00 05:10:00.000000'), NULL, 588, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (45, 42, 'YUL', 'YVR', TO_DSINTERVAL('00 05:10:00.000000'), NULL, 588, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (23, 2, 'YUL', 'ORY', TO_DSINTERVAL('00 06:50:00.000000'), 27000, 772, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (24, 4, 'YUL', 'CDG', TO_DSINTERVAL('00 06:50:00.000000'), 30000, 1139, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (25, 1, 'YUL', 'ORY', TO_DSINTERVAL('00 07:00:00.000000'), 30000, 730, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (27, 21, 'YUL', 'SYD', TO_DSINTERVAL('00 22:35:00.000000'), NULL, 3229, 1);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (28, 6, 'YUL', 'CUN', TO_DSINTERVAL('00 04:30:00.000000'), NULL, 672, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (29, 5, 'YUL', 'CUN', TO_DSINTERVAL('00 04:30:00.000000'), NULL, 570, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (30, 22, 'YUL', 'CUN', TO_DSINTERVAL('00 04:30:00.000000'), NULL, 504, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (31, 5, 'YUL', 'CUN', TO_DSINTERVAL('00 04:30:00.000000'), NULL, 610, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (32, 6, 'YUL', 'CUN', TO_DSINTERVAL('00 04:30:00.000000'), NULL, 678, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (33, 23, 'YUL', 'LAX', TO_DSINTERVAL('00 06:05:00.000000'), NULL, 870, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (34, 5, 'YUL', 'LAX', TO_DSINTERVAL('00 06:00:00.000000'), NULL, 1152, 0);

INSERT INTO vol("ID_VOL", "ID_AVION", "CODE_IATA_DÉPART", "CODE_IATA_DESTINATION", "DURÉE_DE_VOL", "CARBURANT_CONSOMMER", "PRIX", "TRANSFER") 
VALUES (35, 24, 'YUL', 'SEA', TO_DSINTERVAL('00 16:40:00.000000'), NULL, 437, 1);


COMMIT;


ALTER USER Billeterie IDENTIFIED BY oracle ACCOUNT UNLOCK;
GRANT CONNECT, RESOURCE TO Billeterie;
GRANT CREATE SESSION TO Billeterie;

BEGIN
  ORDS.ENABLE_SCHEMA(
    p_enabled             => TRUE,
    p_schema              => 'BILLETERIE',      -- Nom du schéma (MAJUSCULES)
    p_url_mapping_type    => 'BASE_PATH',  -- Type de mapping
    p_url_mapping_pattern => 'scott',      -- Préfixe dans l'URL
    p_auto_rest_auth      => FALSE         -- Pas d'auth (dev)
  );
  COMMIT;
END;
/



BEGIN
  ORDS.ENABLE_OBJECT(
    p_enabled        => TRUE,
    p_schema         => 'BILLETERIE',
    p_object         => 'CLIENT',    
    p_object_type    => 'TABLE',
    p_auto_rest_auth => FALSE
  );
  COMMIT;
END;
/


BEGIN
  ORDS.ENABLE_OBJECT(
    p_enabled        => TRUE,
    p_schema         => 'BILLETERIE',
    p_object         => 'AVION',   
    p_object_type    => 'TABLE',
    p_auto_rest_auth => FALSE
  );
  COMMIT;
END;
/


BEGIN
  ORDS.ENABLE_OBJECT(
    p_enabled        => TRUE,
    p_schema         => 'BILLETERIE',
    p_object         => 'BILLET',    -- ← Changer ici le nom de votre table
    p_object_type    => 'TABLE',
    p_auto_rest_auth => FALSE
  );
  COMMIT;
END;
/



BEGIN
  ORDS.ENABLE_OBJECT(
    p_enabled        => TRUE,
    p_schema         => 'BILLETERIE',
    p_object         => 'VOL',    -- ← Changer ici le nom de votre table
    p_object_type    => 'TABLE',
    p_auto_rest_auth => FALSE
  );
  COMMIT;
END;
/


BEGIN
  ORDS.ENABLE_OBJECT(
    p_enabled        => TRUE,
    p_schema         => 'BILLETERIE',
    p_object         => 'DÉPART',    -- ← Changer ici le nom de votre table
    p_object_type    => 'TABLE',
    p_auto_rest_auth => FALSE
  );
  COMMIT;
END;
/


BEGIN
  ORDS.ENABLE_OBJECT(
    p_enabled        => TRUE,
    p_schema         => 'BILLETERIE',
    p_object         => 'DESTINATION',    -- ← Changer ici le nom de votre table
    p_object_type    => 'TABLE',
    p_auto_rest_auth => FALSE
  );
  COMMIT;
END;
/