CREATE TABLE client(
    id_client NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    prénom VARCHAR2(100) NOT NULL,
    nom VARCHAR2(100) NOT NULL,
    date_naissance DATE DEFAULT SYSDATE NOT NULL,
    email VARCHAR2(100)
);
INSERT INTO client (prénom, nom, email) VALUES ('James', 'Bond', 'jbond@gmail.com');
INSERT INTO client (prénom, nom, email) VALUES ('Justin', 'Bieber', 'jbieber@gmail.com');

CREATE TABLE avion (
    id_avion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    couleur VARCHAR2(100) DEFAULT 'Blanc',
    modèle VARCHAR2(100) NOT NULL,
    compagnie VARCHAR2(100) NOT NULL
);
INSERT INTO avion (couleur, modèle, compagnie) VALUES ('Rouge', 'ABC-123', 'St-Hubert');
INSERT INTO avion (modèle, compagnie) VALUES ('DEF-456', 'North Texas Regional');
INSERT INTO avion (modèle, compagnie) VALUES ('GHI-789', 'Metropolitan Area');
INSERT INTO avion (modèle, compagnie) VALUES ('JKL-012', 'Orly');
INSERT INTO avion (modèle, compagnie) VALUES ('MNO-345', 'Canberra Airport');
INSERT INTO avion (modèle, compagnie) VALUES ('PQR-678', 'Toluca-A.Lopez Mateos');

CREATE TABLE départ (
    code_iata VARCHAR2(3) NOT NULL PRIMARY KEY,
    pays VARCHAR2(100) NOT NULL,
    capacité NUMBER
);
INSERT INTO départ (code_iata, pays, capacité) VALUES ('YHU', 'Canada', 200);
INSERT INTO départ (code_iata, pays, capacité) VALUES ('PNX', 'États-Unis', 250);
INSERT INTO départ (code_iata, pays, capacité) VALUES ('TYO', 'Japon', 300);
INSERT INTO départ (code_iata, pays, capacité) VALUES ('ORY', 'France', 200);
INSERT INTO départ (code_iata, pays, capacité) VALUES ('CBR', 'Australie', 250);
INSERT INTO départ (code_iata, pays, capacité) VALUES ('TLC', 'Mexique', 300);

CREATE TABLE destination (
    code_iata VARCHAR2(3) NOT NULL PRIMARY KEY,
    pays VARCHAR2(100) NOT NULL,
    capacité NUMBER,
    image_de_destination VARCHAR2(100) NOT NULL,
    en_feu BOOLEAN NOT NULL
);
INSERT INTO destination (code_iata, pays, capacité, image_de_destination, en_feu) VALUES ('YHU', 'Canada', 200, 'montreal.png', FALSE);
INSERT INTO destination (code_iata, pays, capacité, image_de_destination, en_feu) VALUES ('PNX', 'États-Unis', 250, 'texas.png', FALSE);
INSERT INTO destination (code_iata, pays, capacité, image_de_destination, en_feu) VALUES ('TYO', 'Japon', 300, 'tokyo.png', FALSE);
INSERT INTO destination (code_iata, pays, capacité, image_de_destination, en_feu) VALUES ('ORY', 'France', 200, 'paris.png', TRUE);
INSERT INTO destination (code_iata, pays, capacité, image_de_destination, en_feu) VALUES ('CBR', 'Australie', 250, 'canberra.png', TRUE);
INSERT INTO destination (code_iata, pays, capacité, image_de_destination, en_feu) VALUES ('TLC', 'Mexique', 300, 'mexico_city.png', TRUE);

CREATE TABLE vol (
    id_vol NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_avion NUMBER NOT NULL,
    code_iata_départ VARCHAR2(3) NOT NULL,
    code_iata_destination VARCHAR2(3) NOT NULL,
    durée_de_vol INTERVAL DAY TO SECOND,
    carburant_consommer NUMBER(10, 2),
    CONSTRAINT fk_avion FOREIGN KEY (id_avion) REFERENCES avion(id_avion),
    CONSTRAINT fk_départ FOREIGN KEY (code_iata_départ) REFERENCES départ(code_iata),
    CONSTRAINT fk_destination FOREIGN KEY (code_iata_destination) REFERENCES destination(code_iata)
);
INSERT INTO vol (id_avion, code_iata_départ, code_iata_destination) VALUES (2, 'PNX', 'TYO');
INSERT INTO vol (id_avion, code_iata_départ, code_iata_destination) VALUES (3, 'TYO', 'YHU');
INSERT INTO vol (id_avion, code_iata_départ, code_iata_destination) VALUES (1, 'YHU', 'PNX');

CREATE TABLE billet (
    id_billet NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_client NUMBER NOT NULL,
    id_vol NUMBER NOT NULL,
    classe VARCHAR2(100) NOT NULL,
    prix NUMBER(10, 2) NOT NULL,
    date_créé DATE DEFAULT SYSDATE NOT NULL,
    date_départ DATE NOT NULL,
    date_arrivé DATE NOT NULL,
    heure_départ VARCHAR(100),
    heure_arrivée VARCHAR(100),
    CONSTRAINT fk_client FOREIGN KEY (id_client) REFERENCES client(id_client),
    CONSTRAINT fk_vol FOREIGN KEY (id_vol) REFERENCES vol(id_vol)
);
INSERT INTO billet (id_client, id_vol, classe, prix, date_départ, date_arrivée, heure_départ, date_arrivée)
VALUES (1, 1, 'Standard', 99.99, SYSDATE, SYSDATE, '2:00AM', '8:00AM');
INSERT INTO billet (id_client, id_vol, classe, prix, date_départ, date_arrivée, heure_départ, date_arrivée)
VALUES (2, 1, 'Standard', 99.99, SYSDATE, SYSDATE, '2:00AM', '8:00AM');
INSERT INTO billet (id_client, id_vol, classe, prix, date_départ, date_arrivée, heure_départ, date_arrivée)
VALUES (1, 2, 'Business', 149.99, SYSDATE, SYSDATE, '10:00AM', '4:00PM');
INSERT INTO billet (id_client, id_vol, classe, prix, date_départ, date_arrivée, heure_départ, date_arrivée)
VALUES (2, 2, 'Business', 149.99, SYSDATE, SYSDATE, '10:00AM', '4:00PM');
INSERT INTO billet (id_client, id_vol, classe, prix, date_départ, date_arrivée, heure_départ, date_arrivée)
VALUES (1, 3, 'Business', 299.99, SYSDATE, SYSDATE, '6:00PM', '8:00PM');
INSERT INTO billet (id_client, id_vol, classe, prix, date_départ, date_arrivée, heure_départ, date_arrivée)
VALUES (2, 3, 'Business', 299.99, SYSDATE, SYSDATE, '6:00PM', '8:00PM');